### ISSUE TITLE
When can we next meet ?

### ISSUE THREAD

**Issue by amalnathsathyan** [amalnathsathyan/OwlSwap#8]
Hope we get back on call soon  @adityaok0  @amalnathsathyan  @deca28 ! Meanwhile, let me check @gitpoap-bot !

**Comment by amalnathsathyan** [comment]
Nice job @adityaok0 ! Here's a GitPOAP to show our appreciation @gitpoap-bot

**Comment by adityaok0** [comment]
Thanks. Closing the issue
